from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QMovie
from PyQt5.QtCore import Qt


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")  # set the name of the mainwindow object
        MainWindow.resize(310, 460)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.labelHello = QtWidgets.QLabel(self.centralwidget)
        self.labelHello.setGeometry(QtCore.QRect(65, 180, 180, 35))
        self.labelHello.setFont(font)
        self.labelHello.setStyleSheet("color: rgb(0, 117, 210);")
        self.labelHello.setTextFormat(QtCore.Qt.AutoText)
        self.labelHello.setWordWrap(True)
        self.labelHello.setObjectName("labelHello")
        self.labelHello.setAlignment(Qt.AlignCenter)

        self.labelSorry = QtWidgets.QLabel(self.centralwidget)
        self.labelSorry.setGeometry(QtCore.QRect(65, 180, 180, 35))
        self.labelSorry.setFont(font)
        self.labelSorry.setStyleSheet("color: rgb(0, 117, 210);")
        self.labelSorry.setTextFormat(QtCore.Qt.AutoText)
        self.labelSorry.setWordWrap(True)
        self.labelSorry.setObjectName("labelSorry")
        self.labelSorry.setAlignment(Qt.AlignCenter)

        self.labelWaked = QtWidgets.QLabel(self.centralwidget)
        self.labelWaked.setGeometry(QtCore.QRect(65, 180, 180, 35))
        self.labelWaked.setFont(font)
        self.labelWaked.setStyleSheet("color: rgb(209, 129, 253);")
        self.labelWaked.setTextFormat(QtCore.Qt.AutoText)
        self.labelWaked.setWordWrap(True)
        self.labelWaked.setObjectName("labelWaked")
        self.labelWaked.setAlignment(Qt.AlignCenter)

        self.label2click = QtWidgets.QLabel(self.centralwidget)
        self.label2click.setGeometry(QtCore.QRect(45, 400, 220, 35))
        self.label2click.setFont(font)
        self.label2click.setStyleSheet("color: rgb(111, 208, 204);")
        self.label2click.setTextFormat(QtCore.Qt.AutoText)
        self.label2click.setWordWrap(True)
        self.label2click.setObjectName("label2click")
        self.label2click.setAlignment(Qt.AlignCenter)

        # font = QtGui.QFont()
        # font.setFamily("Calibri")
        # font.setPointSize(14)
        self.labelHH = QtWidgets.QLabel(self.centralwidget)
        self.labelHH.setGeometry(QtCore.QRect(65, 150, 180, 21))
        self.labelHH.setFont(font)
        self.labelHH.setStyleSheet("color: rgb(0, 117, 210);")
        self.labelHH.setWordWrap(True)
        self.labelHH.setObjectName("labelHH")

        self.labelH1 = QtWidgets.QLabel(self.centralwidget)
        self.labelH1.setGeometry(QtCore.QRect(65, 180, 180, 51))
        self.labelH1.setFont(font)
        self.labelH1.setStyleSheet("color: rgb(0, 117, 210);")
        self.labelH1.setWordWrap(True)
        self.labelH1.setObjectName("labelH1")

        self.labelH2 = QtWidgets.QLabel(self.centralwidget)
        self.labelH2.setGeometry(QtCore.QRect(65, 230, 180, 51))
        self.labelH2.setFont(font)
        self.labelH2.setStyleSheet("color: rgb(0, 117, 210);")
        self.labelH2.setWordWrap(True)
        self.labelH2.setObjectName("labelH2")

        self.labelH3 = QtWidgets.QLabel(self.centralwidget)
        self.labelH3.setGeometry(QtCore.QRect(65, 280, 180, 51))
        self.labelH3.setFont(font)
        self.labelH3.setStyleSheet("color: rgb(0, 117, 210);")
        self.labelH3.setWordWrap(True)
        self.labelH3.setObjectName("labelH3")

        self.labelH4 = QtWidgets.QLabel(self.centralwidget)
        self.labelH4.setGeometry(QtCore.QRect(65, 330, 180, 51))
        self.labelH4.setFont(font)
        self.labelH4.setStyleSheet("color: rgb(0, 117, 210);")
        self.labelH4.setWordWrap(True)
        self.labelH4.setObjectName("labelH4")

        self.labelRec= QtWidgets.QLabel(self.centralwidget)
        self.labelRec.setGeometry(QtCore.QRect(65, 180, 180, 35))
        self.labelRec.setFont(font)
        self.labelRec.setStyleSheet("color: rgb(0, 117, 210);")
        self.labelRec.setWordWrap(True)
        self.labelRec.setObjectName("labelRec")
        self.labelRec.setAlignment(Qt.AlignCenter)

        self.voiceFig = QtWidgets.QLabel(self.centralwidget)
        self.voiceFig.setGeometry(QtCore.QRect(85, 50, 150, 100))
        self.voiceFig.setText("")
        self.gif = QMovie("resources/index.gif")
        self.gifNorm = QMovie('resources/normal.gif')
        self.gifRecing = QMovie('resources/recognizing.gif')
        self.voiceFig.setMovie(self.gif)
        self.gif.start()
        self.gifNorm.start()
        self.gifRecing.start()
        self.voiceFig.setScaledContents(True)
        self.voiceFig.setObjectName("voiceFig")

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Voice Assistant"))
        self.labelHello.setText(_translate("MainWindow", "Say \'Hello\' to wake me up!"))
        self.labelWaked.setText("Hi~ what can I help you?")
        self.labelSorry.setText("Sorry I couldn't hear you, please say 'Hello' again.")
        self.label2click.setText(_translate("MainWindow", "Double click to show help list."))
        self.labelHH.setText(_translate("MainWindow", "You can say:"))
        self.labelH1.setText(_translate("MainWindow", "1. \"Music\"-Play a music"))
        self.labelH2.setText(_translate("MainWindow", "2. \"Note\"-Open Notability.app"))
        self.labelH3.setText(_translate("MainWindow", "3. \"Google\"-Open Google.com"))
        self.labelH4.setText(_translate("MainWindow", "4. \"Calculate\"-Open Calculator"))
        self.labelRec.setText("Recognizing...")
        self.labelHH.setVisible(False)
        self.labelH1.setVisible(False)
        self.labelH2.setVisible(False)
        self.labelH3.setVisible(False)
        self.labelH4.setVisible(False)
        self.labelWaked.setVisible(False)
        self.labelRec.setVisible(False)
